name: SonarQube Analysis

on:
  push:
    branches:
      - main # or any branch you want to analyze
  pull_request:
    branches:
      - main # or any branch you want to analyze

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Cache SonarQube scanner
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.java') }}
        restore-keys: |
          ${{ runner.os }}-sonar-

    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@v1
      with:
        sonar-host-url: 'http://0.0.0.0:9000'  # SonarQube Docker instance URL
        sonar-token: ${{ secrets.SONAR_TOKEN }}
        projectKey: 'tcshabin_foundation'  # Replace with your project key
        projectName: 'foundation'  # Replace with your project name
